# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='body',
        ),
    ]
