# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 17:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_about_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
