# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160927_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('imagem_src', models.TextField(blank=True, null=True)),
                ('redesocial', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram')], max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-data',),
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts Instagram',
            },
        ),
    ]
