# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_testimonials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='trip_advisor',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='youtube',
        ),
    ]
