# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20161006_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagem_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
