# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20161006_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='main_image',
        ),
    ]
