# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('home', '0021_auto_20161011_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTokenInstagramSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INSTAGRAM_USER_ID', models.TextField()),
                ('INSTAGRAM_CLIENT_ID', models.TextField()),
                ('INSTAGRAM_CLIENT_SECRET', models.TextField()),
                ('INSTAGRAM_ACCESS_TOKEN', models.TextField()),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
